server: server.c ../clientserversockets.c
	gcc -o server server.c ../clientserversockets.c -l pthread
seqServer: seqServer.c ../clientserversockets.c
	gcc -o seqServer seqServer.c ../clientserversockets.c

client: client.c ../clientserversockets.c
	gcc -o client client.c ../clientserversockets.c

